Using Bootstrap Newsweek page Milestone 1
jurgen1c/Using-Bootstrap-Newsweek-Page pull request #1
Opened 2020-08-03 22:12 UTC by jurgen1c

#### Using Bootstrap 
In this branch we:

- Added HTML & CSS
- Added styling with Bootstrap CDN 
- Added relevant content.

2020-08-03 23:26 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

#### Hey @jurgen1c and @Ceci007 

You did a very good job on this project. The mobile screen size looks quite nice, and the large screen also looks great.

However, in order to achieve mastery, there are a few aspects to improve:

- [x] I do not see the layout for the tablet screen size. You are missing the design for a whole screen size. Kindly address that.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89236359-b9764c00-d5c6-11ea-9ae3-da9f8fa17061.png) |![image](https://user-images.githubusercontent.com/61479648/89236374-c2ffb400-d5c6-11ea-9954-ff90958ed0bb.png)|

- [x] The general fonts are off. Try to make more like the original.

- [x] Check the inline comments below.

- [x] The order on the mobile screen size is wrong. 
#### It should be: Top Story => Featured Stories => The Debate => Opinion => More Stories => My Turn => In the magazine. 
Yours is: Top Story => My Turn => More Stories => The debate => Opinion => Featured Stories => In the magazine.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-03 23:26 UTC, expjazz commented on index.html
> +            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
- [x] The page is overflowing as the width diminishes.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89234427-584c7980-d5c2-11ea-9664-97f135285077.png) |![image](https://user-images.githubusercontent.com/61479648/89234459-669a9580-d5c2-11ea-8547-28e9d6f29e97.png) |

- [x] The page breaks in the medium screen size.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/89234564-a497b980-d5c2-11ea-98c8-0fd66463a26e.png) | ![image](https://user-images.githubusercontent.com/61479648/89234578-abbec780-d5c2-11ea-9a05-2b841301a7e1.png) |

- [x] The navbar breaks at the mobile screen size (700px)

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89234666-d741b200-d5c2-11ea-9c8c-c918b4d5db9d.png)|![image](https://user-images.githubusercontent.com/61479648/89234683-e0328380-d5c2-11ea-8532-ffc59f972e18.png)|

2020-08-03 23:26 UTC, expjazz commented on index.html
> +              </a>
- [x] The design in the mobile and medium screens is completely off (font-sizes and font-weights). It is also breaking

- [x] Try to focus on the details. It needs to be close to the original.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89234887-651d9d00-d5c3-11ea-94a2-22867261d4f7.png)| ![image](https://user-images.githubusercontent.com/61479648/89234906-72d32280-d5c3-11ea-9459-556c0969d76e.png)|

2020-08-03 23:26 UTC, expjazz commented on index.html
> +          <!--Free Sign-Up-->
- [x] You missed a section here. (don't mind the navbar in the screenshot)

![image](https://user-images.githubusercontent.com/61479648/89235009-c04f8f80-d5c3-11ea-934e-d5af59591046.png)

2020-08-03 23:26 UTC, expjazz commented on index.html
> +      </div>
- [ ] The height and alignment of the images are too different. Try to make closer to the original.


| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89235387-70bd9380-d5c4-11ea-9b23-c0cd039484d4.png)| ![image](https://user-images.githubusercontent.com/61479648/89235350-5daac380-d5c4-11ea-852f-720f365fddc5.png) |

2020-08-03 23:26 UTC, expjazz commented on index.html
> +              <h2 class="card-title">Trump's Coronavirus, Protest and Russia Ratings Plummet to 30s</h2>
- [ ] Fonts are off here as well

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89235756-33a5d100-d5c5-11ea-967f-308f50d050a9.png) | ![image](https://user-images.githubusercontent.com/61479648/89235779-3c96a280-d5c5-11ea-8eb3-9de44094dae3.png) |

2020-08-03 23:26 UTC, expjazz commented on index.html
> +            <div>
- [ ] In the small screen size, it does not have an image.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89235930-9e570c80-d5c5-11ea-8ed3-eecdac6e06b2.png) |![image](https://user-images.githubusercontent.com/61479648/89235946-a616b100-d5c5-11ea-8de4-aae377413663.png) |

- [ ] IT is breaking at 1022 px, and overflowing

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/89236029-e413d500-d5c5-11ea-96fb-1e17aac7b32e.png) | ![image](https://user-images.githubusercontent.com/61479648/89236057-eece6a00-d5c5-11ea-98a1-329c1cc2d084.png) |

2020-08-03 23:26 UTC, expjazz commented on index.html
> +          <div class="mr-2">
- [ ] copyright alignment on the mobile screen is different. Also, pay attention to the font styling.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89236167-3b19aa00-d5c6-11ea-908b-722d9781ebcf.png) | ![image](https://user-images.githubusercontent.com/61479648/89236195-4d93e380-d5c6-11ea-8bad-0b025b6bad2b.png) |

2020-08-04 00:00 UTC, jurgen1c commented on index.html
> +          <!--Free Sign-Up-->
Hello,
This is an Ad as you can see from the title says sponsored insight and it doesn't show up with an add blocker. we thought we shouldn't include ads or should we?

2020-08-04 13:46 UTC, jurgen1c commented
![newsweek no ads](https://user-images.githubusercontent.com/39919179/89301205-9da29280-d626-11ea-92c6-ddd0451c79ef.png)
 This is how the page looks to us without any ads

2020-08-04 18:23 UTC, expjazz requested changes
## Status: Changes required :recycle: 

You did a very good job working on the changes I requested, and we are almost done. I saw two more details that came after what you changed, but they are minor and it won't take much time.

#### However, there is one problem: The order of the sections in the mobile version is wrong. Kindly address that (you need to make it in the same as the original; To do so, you might need to use extra HTML).

Again, your project look really great.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-04 18:23 UTC, expjazz commented on index.html
> +                See why nearly a quarter of a million subscribers begin their day with the Starting 5.
- [ ] This section looks much better. You just need to just the SUBSCRIBE to be equal (the layout), put some border on THE STARTING FIVE, and centralize both.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89329531-57b8ef00-d665-11ea-9377-6f32fce7a443.png) |![image](https://user-images.githubusercontent.com/61479648/89329597-6bfcec00-d665-11ea-8238-81a047f22549.png)  |

2020-08-04 18:23 UTC, expjazz commented on index.html
> +          </li>
- [ ] This section needs more width.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89329854-cac26580-d665-11ea-989c-f8e64fd92c97.png) |![image](https://user-images.githubusercontent.com/61479648/89329902-dca40880-d665-11ea-9b82-092b7eccfbd3.png) |

2020-08-04 20:03 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

You did a fine job on this project :100: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-04 20:05 UTC, merged